spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 123456

  redis:
    database: 0
    port: 6379
    host: localhost
    timeout: 10000
    password:
    jedis:
      pool:
        max-active: 10
        max-wait: 10000
        max-idle: 8
        min-idle: 1

server:
  port: 9090
